print ("Hello World")
print ("My name is BURIN")
print ("call Me Jame")
print ("Learned from Nakae ")
print ("educational NPU ")
print ("Nakhon Phanom Province ")

print ("studying in the second 4 year")
print ("Learned IT")
print ("Faculty of Management Science")
print ("Nakhon Phanom University ")
print ("In the future I want to work as an IT employee")
